apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=        # "admin" em base64
  POSTGRES_PASSWORD: c2VjcmV0cGFzcw==  # "secretpass" em base64
  REDIS_PASSWORD: cmVkaXNwYXNz      # "redispass" em base64
